---
name: django-play
services:
  appserver:
    type: python
    # NOTE: this entire Landofile hard codes a path to an app we assume exists. If you have a different
    # name for your app, you'll have to change all occurences of 'firstapp' to whatever your app is named.
    command: su -c 'python /app/firstapp/manage.py runserver 0.0.0.0:8000 -v 3' www-data
    build:
      - cd /app && pip install --upgrade pip && pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org -r requirements.txt 
    scanner: true
    overrides:
      ports:
        - '8000:8000'
      environment:
        # NOTE: change this path to match your app name
        PYTHONPATH: "/app/firstapp"
        DJANGO_SETTINGS_MODULE: "firstapp.settings"
    moreHttpPorts:
      - '8000'
  db:
    # NOTE: the credentials below are the default for Lando, don't bother trying to change them
    type: postgres:10
    portforward: true
    creds:
      user: postgres
      password: 
      database: django-play

tooling:
  django-admin:
    service: appserver
    cmd: django-admin
  python:
    service: appserver
    cmd: python
  manage:
    service: appserver
    # NOTE: change this path to match your app name
    cmd: cd /app/firstapp && python manage.py
  psql:
    service: db
    cmd: psql -U postgres
  'db-import <file>':
    service: :host
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    options:
      host:
        description: The database service to use
        default: db
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: true
